<?php

namespace Youbar\EasyCrud\Tests\Fixtures\Requests;

use Illuminate\Foundation\Http\FormRequest;

/**
 * Flat layout, as generated by `php artisan make:model -a`.
 */
class StorePostRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    /**
     * @return array<string, mixed>
     */
    public function rules(): array
    {
        return ['title' => 'required|string|max:255'];
    }
}
